# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.define "elita", primary: true do |elita|
  
    #fixes tty issue
    elita.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    
    elita.vm.provider "virtualbox" do |v, override|
      override.vm.box = "ubuntu/trusty64"
    end
    
    elita.vm.provider "parallels" do |v, override|
      override.vm.box = "parallels/ubuntu-14.04"
    end
    
    elita.vm.provider "parallels" do |v|
      v.name = "elita_vagrant"
      v.memory = 1024
      v.cpus = 2
    end

    elita.vm.network "private_network", ip: "10.37.129.100"
  
    elita.vm.synced_folder "salt/state-tree", "/srv/salt"
    
    elita.vm.synced_folder "salt/keys", "/srv/keys"
  
    elita.vm.synced_folder "..", "/home/ubuntu/elita"
  
    elita.vm.provision :salt do |salt|

      salt.master_config = "salt/master"
        
      salt.master_key = "salt/keys/master.pem"
      salt.master_pub = "salt/keys/master.pub"
      
      salt.seed_master = {server0: "salt/keys/minion0.pub"}
        
      salt.run_highstate = false
      salt.install_master = true
      salt.no_minion = true
    end
    
    elita.vm.provision :shell, path: "provision-elita.sh"
  
  end
  
  config.vm.define "server0" do |server0|
    
    #fixes tty issue
    server0.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    
    server0.vm.provider "virtualbox" do |v, override|
      override.vm.box = "ubuntu/trusty64"
    end
    
    server0.vm.provider "parallels" do |v, override|
      override.vm.box = "parallels/ubuntu-14.04"
    end
    
    server0.vm.provider "parallels" do |v|
      v.name = "server0_vagrant"
      v.memory = 1024
      v.cpus = 2
    end
    
    server0.vm.network "private_network", ip: "10.37.129.101"
  
    #server0.vm.synced_folder "salt/state-tree", "/srv/salt"
  
    server0.vm.provision :salt do |salt|

      salt.minion_config = "salt/minion0"
        
      salt.minion_key = "salt/keys/minion0.pem"
      salt.minion_pub = "salt/keys/minion0.pub"
        
      salt.run_highstate = true
    end 

  end

end
